upstream frontend        { server frontend:3000; }
upstream user_service    { server user-service:8002; }
upstream course_service  { server course-service:8001; }
upstream analytics_service { server analytics-service:8003; }
upstream ai_tutor_service  { server ai-tutor-service:8004; }

server {
    listen 80;
    server_name localhost;
    client_max_body_size 100M;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;

    location / {
        proxy_pass http://frontend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /api/auth/     { proxy_pass http://user_service;      proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
    location /api/users/    { proxy_pass http://user_service;      proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
    location /api/courses/  { proxy_pass http://course_service;    proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
    location /api/lessons/  { proxy_pass http://course_service;    proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
    location /api/enrollments/ { proxy_pass http://course_service; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
    location /api/analytics/{ proxy_pass http://analytics_service; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
    location /api/ai/ {
        proxy_pass http://ai_tutor_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 120s;
    }

    location /health {
        return 200 '{"status":"ok","gateway":"nginx"}';
        add_header Content-Type application/json;
    }
}
